### ISSUE TITLE
[GestionGeo] Analyser la BDD existante

### ISSUE THREAD

**Issue by Jean-Roc** [meldig/SQL#122]
Les tables qui composent la base de données connaissent les difficultés suivantes :
- ne comportent aucunes contraintes ou références
- l'insertion depuis une action du client dynmap se fait via une série de requête http POST, la moindre coupure réseau peut faire qu'une transaction n'aura pas aboutie et que le résultat en base ne sera pas conforme
- la traduction des requêtes de MySQL vers Oracle n'arrange rien

Il faudrait :
- faire un schéma du modèle physique
- faire les statistiques d'usage sur les colonnes (% null, valeurs distincts, etc.)
- évaluer les géométries

**Comment by Jean-Roc** [comment]
@BaptisteJacq les commentaires peuvent être ajoutés sans impact sur la base de prod

**Comment by Jean-Roc** [comment]
Pour bosser sereinement il faudrait demander à basculer une copie à jour de ces tables sur la plateforme de test (ora11 ou 12 au choix)

**Comment by BaptisteJacq** [comment]
Oui je suis d'accord.
La demande vient d'être envoyée.
J'ai demandé à ce que ce soit fait sur ora11 afin qu'on soit iso entre la prod et la dev.

**Comment by Jean-Roc** [comment]
J'ai refait une demande pour avoir l'accès à data pump import/export, sans ça impossible de concevoir par la suite un script de migration vers MULTI sans une étape manuelle
